@startuml
actor User
participant "TG Bot" as Bot
participant "S3 Storage" as S3
participant "Kafka" as Kafka
participant "Database" as DB
participant "ML Service" as ML


User -> Bot : Отправка файла
activate Bot
Bot -> S3 : Сохранение файла
activate S3
S3 -> Bot : OK
deactivate S3
Bot -> Kafka : Сообщение: "Обработка файла"
activate Kafka
Bot -> User : Подтверждение получения файла
deactivate Bot


Kafka -> Bot : Получение сообщения (обработка файла)
deactivate Kafka
activate Bot
Bot -> DB : Создание записи проверки файла
activate DB
DB -> Bot : OK
deactivate DB
loop По строкам файла
    Bot -> Kafka : Сообщение о проверке отдельного отзыва
    activate Kafka
end
deactivate Bot


Kafka -> Bot : Получение о проверке отдельного отзыва
deactivate Kafka
activate Bot
Bot -> ML : HTTP запрос на проверку строки
activate ML
ML -> Bot : Результат проверки
deactivate ML
Bot -> DB : Сохранение результата
activate DB
DB -> Bot : OK
deactivate DB
deactivate Bot


Bot -> Bot : Планировщик активен (cron)
activate Bot
Bot -> DB : Поиск завершённых файлов
activate DB
DB -> Bot : Список завершённых файлов
deactivate DB
Bot -> User : Отправка отчёта о проверке
deactivate Bot

@enduml
