@startuml
left to right direction

actor "Пользователь" as User

rectangle "Telegram-бот для проверки отзывов" {
    User -- (Просмотреть историю проверок)

    User -- (Отправить текст отзыва)
    (Отправить текст отзыва) ..> (Получение результата проверки) : <<include>>

    User -- (Отправить файл с отзывами)
    (Отправить файл с отзывами) ..> (Получить отчет о проверке файла) : <<include>>
}

@enduml
